In [1]:
import h5py
import numpy as np
import gym 
import gym_routing
from gym.utils import seeding

In [2]:
env = gym.make('Cspp-v0')

[2018-09-19 15:53:48,493] Making new env: Cspp-v0


validation fraciton: 0.7
loading data...
Shift and scale


In [30]:
s = env.reset()
print(s)

path find
(array([[     0.        ,      0.        ,      0.        , ...,
           647.        ,    139.98929687,  36900.        ]]), 0.0, False, {})


In [15]:
s[0][0, 291*2+648*2:291*2+648*3]

array([ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.2,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0

In [ ]:
env.render()
env.render()

True

In [5]:
env.xx

5901.2689158520079

In [6]:
env.yy

5202.2049610801041

In [7]:
env.scalex

0.10167304838257379

In [14]:
env.network["r"][1].start

(27159.257739619294, 540045.44643014809)

In [5]:
env.ppointer

1

In [4]:
env.problem.instance.start

9230

In [9]:
env.problem.graphs['graph1'].out_edges(9425)

OutEdgeDataView([(9425, 3977), (9425, 5308), (9425, 4245), (9425, 4279)])

In [9]:
env.problem.instance.dest

9230

In [22]:
env.edgelist

[353, 354]

In [26]:
env.edgelist

[354]

In [25]:
env.path

[5652, 8911, 3848, 3849]

In [28]:
env.path

[5652, 8911, 3848, 3917]

In [20]:
env.problem.graphs["graph1"][3030][3027]["Index"]

611

In [10]:
env.problem.graphs["graph1"].nodes[9230]

{'Index': 8,
 'c1': inf,
 'c2': inf,
 'c3': inf,
 'r11': inf,
 'r12': inf,
 'r13': inf,
 'visited': 0}

In [14]:
env.network["r"][405]._color.vec4 = (0,1,1,1)

In [48]:
np.sqrt((len(env.problem.graphs["graph1"].nodes))*2 + 4*(len(env.problem.graphs["graph1"].edges)))

56.338264084013097

In [27]:
res = env.step(354)
env.render()
res

(array([[     0.       ,      0.       ,      0.       , ...,
            647.       ,    308.6260952,  45000.       ]]), 0.0, False, {})

In [29]:
res[0][0, 291*2+648*2:291*2+648*3]

array([ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  1. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0

In [10]:
env.problem.numnodes["graph1"]

291

In [14]:
env.problem.numedges["graph1"]

648

In [26]:
res[0][0, 291*2+648*2+611]

0.20000000298023224

In [17]:
res[0].shape

(1, 3176)

In [18]:
291*2+648*4

3174

In [12]:
env.render()

True

In [3]:
data = h5py.File("/media/mSATA/UM/Upper routing simulation/SUMOdata/routingdataset.hdf5", 'r')

In [4]:
data['graph1/route_info']

<HDF5 dataset "route_info": shape (76, 174, 8), type "<f8">

In [5]:
gs = data['graph1/graph_structure']

In [6]:
ri = data['graph1/route_info']

In [7]:
ti = data['graph1/traffic_info']

In [8]:
ri.shape

(76, 174, 8)

In [9]:
ti.shape

(649, 76, 5)

In [10]:
gs.shape

(649, 2)

In [12]:
ti.attrs["featureaxis"]

3

In [13]:
ti.attrs.keys()

[u'id', u'linkaxis', u'stepaxis', u'featureaxis']

In [19]:
ri.attrs["stepaxis"]

1

In [57]:
import networkx as nx

In [58]:
g = nx.DiGraph()

In [64]:
g.add_edge(1,2)
g.add_edge(3,1)
g.add_edge(2,3)
g.add_edge(2,4)

In [65]:
g.out_degree(2)

2

In [22]:
(2,2) in g.edges

False

In [38]:
for idx, link in enumerate(g.edges()):
    print(link[0], idx)

(1, 0)
(2, 1)
(3, 2)


In [41]:
list(g.edges)[1]

(2, 3)

In [31]:
g[1][2]["r1"] = 10

In [11]:
g.nodes[1]["e"] = 10

In [72]:
g.out_edges(2)

OutEdgeDataView([(2, 3), (2, 4)])

In [22]:
g.nodes[1]

{'e': 10}

In [6]:
len(g.nodes())

2

In [9]:
for n in g.nodes:
    print(n)

1
2


In [2]:
nx.__version__

'2.1'

In [6]:
a = 1 if 1 > 0 else 0

In [69]:
a = np.zeros((1,2))
b = np.zeros((1,2))

In [71]:
np.concatenate((a, b), axis = -1)

array([[ 0.,  0.,  0.,  0.]])

In [78]:
a = np.array([1,2,3])
a[np.newaxis,:].shape

(1, 3)